ok

diff --git a/.github/workflows/auto_rebase_all.yml b/.github/workflows/auto_rebase_all.yml
--- a/.github/workflows/auto_rebase_all.yml
+++ b/.github/workflows/auto_rebase_all.yml
@@ -28,7 +28,14 @@ jobs:
       - run: |
           IFS=","
           for branch in $BRANCHES_TO_REBASE; do
-            { git checkout $branch  && git pull && git rebase $ROOT_BRANCH_NAME && git push --force-with-lease && echo "Rebase SUCCEEDED for branch $branch" ;} || { echo "Rebase FAILED for branch $branch" && git rebase --abort ; }
+            { git checkout $branch  && \
+              git pull && \
+              git rebase $ROOT_BRANCH_NAME && \
+              git push --force-with-lease && \
+              echo "Rebase SUCCEEDED for branch $branch" ;} \
+              
+            || { echo "Rebase FAILED for branch $branch" && git rebase --abort ; }
+            
           done
           
 #### Iterate All branches  
@@ -37,8 +44,3 @@ jobs:
 #for branch in "${branches[@]}"; do
 #    # …
 #done
-
-
-
-
-
